words = [
    "atexit",
    "bcc",
    "bcs",
    "bdizc",
    "beq",
    "brk",
    "bmi",
    "bne",
    "bpl",
    "bvc",
    "bvs",
    "clc",
    "cld",
    "clv",
    "cpc",
    "cpx",
    "cpy",
    "eor",
    "iny",
    "jmp",
    "jsr",
    "lda",
    "ldx",
    "ldy",
    "lsr",
    "nop",
    "pha",
    "pla",
    "plp",
    "inx",
    "getitem",
    "iadd",
    "ips",
    "nlines",
    "pyright",
    "radd",
    "rol",
    "roms",
    "ror",
    "rti",
    "rts",
    "sbc",
    "sed",
    "sei",
    "setitem",
    "stx",
    "tay",
    "tcss",
    "txa",
    "txs",
    "tya",
    "upto",
    "wozmon",
]
